rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
language: ruby
before_install:
  - "gem update --system"
before_script:
  - "rake servers:jasig:prep"
  - "bundle exec rake servers:jasig:start &"
  - "bundle exec rake servers:callback:start &"
  - "eval `rake servers:jasig:endpoints`"
  - "eval `rake servers:callback:endpoints`"
