--- !ditz.rubyforge.org,2008-03-06/project 
name: castanet
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: castanet
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 1.0.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2011-02-15 02:22:54.002081 Z
    - yipdw <yipdw@member.fsf.org>
    - created
    - ""
